module.exports = {
	rules: {
		"jsdoc/check-access": "warn",
		"jsdoc/check-alignment": "warn",
		"jsdoc/check-examples": ["warn", {
			"captionRequired": false,
			"paddedIndent": 2,
			"reportUnusedDisableDirectives": true,
			"checkParams": true,
			"checkProperties": true,
		}],
		"jsdoc/check-indentation": ["warn", {
			"excludeTags": ["example", "returns"]
		}],
		"jsdoc/check-line-alignment": ["warn", "always", {
			"customSpacings": {
				"postDelimiter": 1,
				"postTag": 1,
				"postType": 1,
			},
		}],
		"jsdoc/check-param-names": "warn",
		"jsdoc/check-property-names": ["warn", {
			"enableFixer": true,
		}],
		"jsdoc/check-syntax": "off",
		"jsdoc/check-tag-names": ["warn", {
			"enableFixer": true,
		}],
		"jsdoc/check-types": "warn",
		"jsdoc/check-values": "warn",
		"jsdoc/empty-tags": "warn",
		"jsdoc/implements-on-classes": "warn",
		"jsdoc/informative-docs": "warn",
		"jsdoc/match-description": "warn",
		"jsdoc/multiline-blocks": "warn",
		"jsdoc/no-bad-blocks": "warn",
		"jsdoc/no-blank-block-descriptions": "warn",
		"jsdoc/no-defaults": "warn",
		"jsdoc/no-missing-syntax": "off",
		"jsdoc/no-multi-asterisks": "warn",
		"jsdoc/no-restricted-syntax": "warn",
		"jsdoc/no-types": "warn",
		"jsdoc/no-undefined-types": "warn",
		"jsdoc/require-asterisk-prefix": "warn",
		"jsdoc/require-description": "warn",
		"jsdoc/require-description-complete-sentence": "warn",
		"jsdoc/require-example": "warn",
		"jsdoc/require-file-overview": "off",
		"jsdoc/require-hyphen-before-param-description": "warn",
		"jsdoc/require-jsdoc": "warn",
		"jsdoc/require-param": "warn",
		"jsdoc/require-param-description": "warn",
		"jsdoc/require-param-name": "warn",
		"jsdoc/require-param-type": "warn",
		"jsdoc/require-property": "warn",
		"jsdoc/require-property-description": "warn",
		"jsdoc/require-property-name": "warn",
		"jsdoc/require-property-type": "warn",
		"jsdoc/require-returns": "warn",
		"jsdoc/require-returns-check": "warn",
		"jsdoc/require-returns-description": "warn",
		"jsdoc/require-returns-type": "warn",
		"jsdoc/require-throws": "warn",
		"jsdoc/require-yields": "warn",
		"jsdoc/require-yields-check": "warn",
		"jsdoc/sort-tags": "warn",
		"jsdoc/tag-lines": "warn",
		"jsdoc/valid-types": "warn"
	},
};
