module.exports = {
	rules: {
		"array-callback-return": "warn",
		"constructor-super": "error",
		"for-direction": "error",
		"getter-return": "warn",
		"no-async-promise-executor": "warn",
		"no-await-in-loop": "warn",
		"no-class-assign": "error",
		"no-compare-neg-zero": "warn",
		"no-cond-assign": ["error", "always"],
		"no-const-assign": "error",
		"no-constant-binary-expression": "warn",
		"no-constant-condition": "warn",
		"no-constructor-return": "warn",
		"no-control-regex": "warn",
		"no-debugger": "error",
		"no-dupe-args": "error",
		"no-dupe-class-members": "error",
		"no-dupe-else-if": "error",
		"no-dupe-keys": "error",
		"no-duplicate-case": "error",
		"no-duplicate-imports": "error",
		"no-empty-character-class": "error",
		"no-empty-pattern": "error",
		"no-ex-assign": "error",
		"no-fallthrough": "error",
		"no-func-assign": "error",
		"no-import-assign": "error",
		"no-inner-declarations": "warn",
		"no-invalid-regexp": "error",
		"no-irregular-whitespace": "error",
		"no-loss-of-precision": "error",
		"no-misleading-character-class": "error",
		"no-new-native-nonconstructor": "error",
		"no-new-symbol": "error",
		"no-obj-calls": "error",
		"no-promise-executor-return": "error",
		"no-prototype-builtins": "error",
		"no-self-assign": "error",
		"no-self-compare": "error",
		"no-setter-return": "error",
		"no-sparse-arrays": "error",
		"no-template-curly-in-string": "warn",
		"no-this-before-super": "error",
		"no-undef": "error",
		"no-unexpected-multiline": "error",
		"no-unmodified-loop-condition": "error",
		"no-unreachable": "error",
		"no-unreachable-loop": "error",
		"no-unsafe-finally": "error",
		"no-unsafe-negation": "error",
		"no-unsafe-optional-chaining": "error",
		"no-unused-private-class-members": "error",
		"no-unused-vars": "error",
		"no-use-before-define": ["warn", {
			functions: false,
			classes: false,
			variables: true,
			allowNamedExports: false
		}],
		"no-useless-backreference": "error",
		"require-atomic-updates": "error",
		"use-isnan": "error",
		"valid-typeof": "error",
		"accessor-pairs": "error",
		"arrow-body-style": ["error", "as-needed"],
		"block-scoped-var": "error",
		"camelcase": ["warn", {
			properties: "never",
			ignoreDestructuring: true,
			ignoreImports: true,
			ignoreGlobals: true
		}],
		"capitalized-comments": "off",
		"class-methods-use-this": "warn",
		"complexity": ["warn", 4],
		"consistent-return": "error",
		"curly": "error",
		"default-case": "error",
		"default-case-last": "error",
		"default-param-last": "warn",
		"dot-notation": "warn",
		"eqeqeq": ["error", "always"],
		"func-name-matching": "off",
		"func-names": ["warn", "always"],
		"func-style": "off",
		"grouped-accessor-pairs": ["warn", "getBeforeSet"],
		"guard-for-in": "error",
		"id-denylist": ["error", "err", "e", "cb", "callback"],
		"id-length": ["error", {
			min: 1,
			max: 20,
			properties: "never",
			exceptions: ["id", "to"],
		}],
		"id-match": "off",
		"init-declarations": "off",
		"logical-assignment-operators": "off",
		"max-classes-per-file": "off",
		"max-depth": ["error", 4],
		"max-lines": ["error", {
			max: 1000,
			skipBlankLines: false,
			skipComments: false
		}],
		"max-lines-per-function": ["error", {
			max: 500,
			skipBlankLines: false,
			skipComments: false
		}],
		"max-nested-callbacks": ["error", 4],
		"max-params": ["error", 4],
		"max-statements": "off",
		"multiline-comment-style": "off",
		"new-cap": "error",
		"no-alert": "error",
		"no-array-constructor": "error",
		"no-bitwise": "warn",
		"no-caller": "error",
		"no-case-declarations": "error",
		"no-confusing-arrow": "error",
		"no-console": "warn",
		"no-continue": "warn",
		"no-delete-var": "error",
		"no-div-regex": "error",
		"no-else-return": "warn",
		"no-empty": "error",
		"no-empty-function": "error",
		"no-empty-static-block": "error",
		"no-eq-null": "error",
		"no-eval": "error",
		"no-extend-native": "error",
		"no-extra-bind": "error",
		"no-extra-boolean-cast": "error",
		"no-extra-label": "error",
		"no-extra-semi": "error",
		"no-floating-decimal": "error",
		"no-global-assign": "error",
		"no-implicit-coercion": "off",
		"no-implicit-globals": "warn",
		"no-implied-eval": "error",
		"no-inline-comments": "off",
		"no-invalid-this": "error",
		"no-iterator": "error",
		"no-label-var": "error",
		"no-labels": "error",
		"no-lone-blocks": "error",
		"no-lonely-if": "warn",
		"no-loop-func": "error",
		"no-magic-numbers": "warn",
		"no-mixed-operators": "warn",
		"no-multi-assign": "error",
		"no-multi-str": "error",
		"no-negated-condition": "warn",
		"no-nested-ternary": "error",
		"no-new": "error",
		"no-new-func": "error",
		"no-new-wrappers": "error",
		"no-nonoctal-decimal-escape": "warn",
		"no-object-constructor": "error",
		"no-octal": "error",
		"no-octal-escape": "error",
		"no-param-reassign": "error",
		"no-plusplus": ["warn", {
			"allowForLoopAfterthoughts": true
		}],
		"no-proto": "error",
		"no-redeclare": "error",
		"no-regex-spaces": "error",
		"no-restricted-exports": "off",
		"no-restricted-globals": "warn",
		"no-restricted-imports": "off",
		"no-restricted-properties": "off",
		"no-restricted-syntax": "off",
		"no-return-assign": ["error", "always"],
		"no-script-url": "error",
		"no-sequences": "warn",
		"no-shadow": "warn",
		"no-shadow-restricted-names": "error",
		"no-ternary": "off",
		"no-throw-literal": "warn",
		"no-undef-init": "error",
		"no-undefined": "error",
		"no-underscore-dangle": "off",
		"no-unneeded-ternary": "error",
		"no-unused-expressions": "warn",
		"no-unused-labels": "error",
		"no-useless-call": "error",
		"no-useless-catch": "warn",
		"no-useless-computed-key": "error",
		"no-useless-concat": "error",
		"no-useless-constructor": "error",
		"no-useless-escape": "error",
		"no-useless-rename": "warn",
		"no-useless-return": "warn",
		"no-var": "warn",
		"no-void": "error",
		"no-warning-comments": "off",
		"no-with": "error",
		"object-shorthand": "warn",
		"one-var": ["error", {
			var: "never",
			let: "never",
			const: "never"
		}],
		"one-var-declaration-per-line": "off",
		"operator-assignment": "off",
		"prefer-arrow-callback": "off",
		"prefer-const": "error",
		"prefer-destructuring": "off",
		"prefer-exponentiation-operator": "error",
		"prefer-named-capture-group": "error",
		"prefer-numeric-literals": "warn",
		"prefer-object-has-own": "warn",
		"prefer-object-spread": "warn",
		"prefer-promise-reject-errors": "warn",
		"prefer-regex-literals": "warn",
		"prefer-rest-params": "error",
		"prefer-spread": "warn",
		"prefer-template": "warn",
		"quote-props": ["warn", "consistent-as-needed"],
		"radix": ["error", "as-needed"],
		"require-await": "warn",
		"require-unicode-regexp": "error",
		"require-yield": "error",
		"sort-imports": ["warn", {
			"ignoreDeclarationSort": true
		}],
		"sort-keys": ["warn", "asc", {
			minKeys: 6
		}],
		"sort-vars": "off",
		"spaced-comment": "off",
		"strict": "off",
		"symbol-description": "warn",
		"vars-on-top": "warn",
		"yoda": ["error", "never"],
	},
};
