module.exports = {
	rules: {
		// Possible Problems
		"array-callback-return": "warn",
		"constructor-super": "error",
		"for-direction": "error",
		"getter-return": "warn",
		"no-async-promise-executor": "warn",
		"no-await-in-loop": "warn",
		"no-class-assign": "error",
		"no-compare-neg-zero": "warn",
		"no-cond-assign": ["error", "always"],
		"no-const-assign": "error",
		"no-constant-binary-expression": "warn",
		"no-constant-condition": "warn",
		"no-constructor-return": "warn",
		"no-control-regex": "warn",
		"no-debugger": "error",
		"no-dupe-args": "error",
		"no-dupe-class-members": "error",
		"no-dupe-else-if": "error",
		"no-dupe-keys": "error",
		"no-duplicate-case": "error",
		"no-duplicate-imports": "error",
		"no-empty-character-class": "error",
		"no-empty-pattern": "error",
		"no-ex-assign": "error",
		"no-fallthrough": "error",
		"no-func-assign": "error",
		"no-import-assign": "error",
		"no-inner-declarations": "warn",
		"no-invalid-regexp": "error",
		"no-irregular-whitespace": "error",
		"no-loss-of-precision": "error",
		"no-misleading-character-class": "error",
		"no-new-native-nonconstructor": "error",
		"no-new-symbol": "error",
		"no-obj-calls": "error",
		"no-promise-executor-return": "error",
		"no-prototype-builtins": "error",
		"no-self-assign": "error",
		"no-self-compare": "error",
		"no-setter-return": "error",
		"no-sparse-arrays": "error",
		"no-template-curly-in-string": "warn",
		"no-this-before-super": "error",
		"no-undef": "error",
		"no-unexpected-multiline": "error",
		"no-unmodified-loop-condition": "error",
		"no-unreachable": "error",
		"no-unreachable-loop": "error",
		"no-unsafe-finally": "error",
		"no-unsafe-negation": "error",
		"no-unsafe-optional-chaining": "error",
		"no-unused-private-class-members": "error",
		"no-unused-vars": "error",
		"no-use-before-define": ["warn", {
			functions: false,
			classes: false,
			variables: true,
			allowNamedExports: false
		}],
		"no-useless-backreference": "error",
		"require-atomic-updates": "error",
		"use-isnan": "error",
		"valid-typeof": "error",

		// Suggestions
		"accessor-pairs": "error",
		"arrow-body-style": ["error", "as-needed"],
		"block-scoped-var": "error",
		"camelcase": ["warn", {
			properties: "never",
			ignoreDestructuring: true,
			ignoreImports: true,
			ignoreGlobals: true
		}],
		"capitalized-comments": "off",
		"class-methods-use-this": "warn",
		"complexity": ["warn", 4],
		"consistent-return": "error",
		"curly": "error",
		"default-case": "error",
		"default-case-last": "error",
		"default-param-last": "warn",
		"dot-notation": "warn",
		"eqeqeq": ["error", "always"],
		"func-name-matching": "off",
		"func-names": ["warn", "always"],
		"func-style": "off",
		"grouped-accessor-pairs": ["warn", "getBeforeSet"],
		"guard-for-in": "error",
		"id-denylist": ["error", "err", "e", "cb", "callback"],
		"id-length": ["warn", {
			min: 1,
			max: 25,
			properties: "never",
		}],
		"id-match": "off",
		"init-declarations": "off",
		"logical-assignment-operators": "off",
		"max-classes-per-file": "off",
		"max-depth": ["error", 4],
		"max-lines": ["error", {
			max: 1000,
			skipBlankLines: false,
			skipComments: false
		}],
		"max-lines-per-function": ["error", {
			max: 500,
			skipBlankLines: false,
			skipComments: false
		}],
		"max-nested-callbacks": ["warn", 4],
		"max-params": ["warn", 4],
		"max-statements": "off",
		"multiline-comment-style": "off",
		"new-cap": "off",
		"no-alert": "error",
		"no-array-constructor": "error",
		"no-bitwise": "warn",
		"no-caller": "error",
		"no-case-declarations": "error",
		"no-confusing-arrow": "error",
		"no-console": "warn",
		"no-continue": "warn",
		"no-delete-var": "error",
		"no-div-regex": "error",
		"no-else-return": "warn",
		"no-empty": "error",
		"no-empty-function": "error",
		"no-empty-static-block": "error",
		"no-eq-null": "error",
		"no-eval": "error",
		"no-extend-native": "error",
		"no-extra-bind": "error",
		"no-extra-boolean-cast": "error",
		"no-extra-label": "error",
		"no-extra-semi": "error",
		"no-floating-decimal": "error",
		"no-global-assign": "error",
		"no-implicit-coercion": "off",
		"no-implicit-globals": "warn",
		"no-implied-eval": "error",
		"no-inline-comments": "off",
		"no-invalid-this": "error",
		"no-iterator": "error",
		"no-label-var": "error",
		"no-labels": "error",
		"no-lone-blocks": "error",
		"no-lonely-if": "warn",
		"no-loop-func": "error",
		"no-magic-numbers": "off",
		"no-mixed-operators": "warn",
		"no-multi-assign": "error",
		"no-multi-str": "error",
		"no-negated-condition": "warn",
		"no-nested-ternary": "error",
		"no-new": "error",
		"no-new-func": "error",
		"no-new-wrappers": "error",
		"no-nonoctal-decimal-escape": "warn",
		"no-object-constructor": "error",
		"no-octal": "error",
		"no-octal-escape": "error",
		"no-param-reassign": "error",
		"no-plusplus": ["warn", {
			"allowForLoopAfterthoughts": true
		}],
		"no-proto": "error",
		"no-redeclare": "error",
		"no-regex-spaces": "error",
		"no-restricted-exports": "off",
		"no-restricted-globals": "warn",
		"no-restricted-imports": "off",
		"no-restricted-properties": "off",
		"no-restricted-syntax": "off",
		"no-return-assign": ["error", "always"],
		"no-script-url": "error",
		"no-sequences": "warn",
		"no-shadow": "warn",
		"no-shadow-restricted-names": "error",
		"no-ternary": "off",
		"no-throw-literal": "warn",
		"no-undef-init": "error",
		"no-undefined": "warn",
		"no-underscore-dangle": "off",
		"no-unneeded-ternary": "error",
		"no-unused-expressions": "warn",
		"no-unused-labels": "error",
		"no-useless-call": "error",
		"no-useless-catch": "warn",
		"no-useless-computed-key": "error",
		"no-useless-concat": "error",
		"no-useless-constructor": "error",
		"no-useless-escape": "error",
		"no-useless-rename": "warn",
		"no-useless-return": "warn",
		"no-var": "warn",
		"no-void": "error",
		"no-warning-comments": "off",
		"no-with": "error",
		"object-shorthand": "warn",
		"one-var": ["error", {
			var: "never",
			let: "never",
			const: "never"
		}],
		"one-var-declaration-per-line": "off",
		"operator-assignment": "off",
		"prefer-arrow-callback": "off",
		"prefer-const": "error",
		"prefer-destructuring": "off",
		"prefer-exponentiation-operator": "error",
		"prefer-named-capture-group": "warn",
		"prefer-numeric-literals": "warn",
		"prefer-object-has-own": "warn",
		"prefer-object-spread": "warn",
		"prefer-promise-reject-errors": "warn",
		"prefer-regex-literals": "warn",
		"prefer-rest-params": "error",
		"prefer-spread": "warn",
		"prefer-template": "warn",
		"quote-props": "off",
		"radix": ["error", "as-needed"],
		"require-await": "warn",
		"require-unicode-regexp": "warn",
		"require-yield": "error",
		"sort-imports": "off",
		"sort-keys": "off",
		"sort-vars": "off",
		"spaced-comment": "off",
		"strict": "off",
		"symbol-description": "warn",
		"vars-on-top": "warn",
		"yoda": ["error", "never"],

		// Layout & Formatting
		"array-bracket-newline": ["error", "consistent"],
		"array-bracket-spacing": ["error", "never"],
		"array-element-newline": ['error', 'consistent'],
		"arrow-parens": "off",
		"arrow-spacing": ["error", {
			"before": true,
			"after": true,
		}],
		"block-spacing": "error",
		"brace-style": "error",
		"comma-dangle": "off",
		"comma-spacing": ["error", {
			"before": false,
			"after": true
		}],
		"comma-style": ["error", "last"],
		"computed-property-spacing": ["error", "never"],
		"dot-location": "off",
		"eol-last": "off",
		"func-call-spacing": ["error", "never"],
		"function-call-argument-newline": ["error", "consistent"],
		"function-paren-newline": ["error", "consistent"],
		"generator-star-spacing": ["error", {
			"before": true,
			"after": false
		}],
		"implicit-arrow-linebreak": "off",
		"indent": "off",
		"jsx-quotes": "off",
		"key-spacing": ["error", {
			"beforeColon": false,
			"afterColon": true,
			"mode": "strict",
		}],
		"keyword-spacing": ["error", {
			"before": true,
			"after": true,
		}],
		"line-comment-position": "off",
		"linebreak-style": "off",
		"lines-around-comment": "off",
		"lines-between-class-members": ["error", "always"],
		"max-len": "off",
		"max-statements-per-line": ["error", {
			"max": 1,
		}],
		"multiline-ternary": ["warn", "always-multiline"],
		"new-parens": "error",
		"newline-per-chained-call": ["error", {
			"ignoreChainWithDepth": 3,
		}],
		"no-extra-parens": "error",
		"no-mixed-spaces-and-tabs": ["error", "smart-tabs"],
		"no-multi-spaces": "error",
		"no-multiple-empty-lines": ["error", {
			"max": 2,
		}],
		"no-tabs": "off",
		"no-trailing-spaces": "error",
		"no-whitespace-before-property": "error",
		"nonblock-statement-body-position": "off",
		"object-curly-newline": ["error", {
			"multiline": true,
			"minProperties": 4,
			"consistent": true,
		}],
		"object-curly-spacing": ["error", "always"],
		"object-property-newline": "off",
		"operator-linebreak": ["error", "after"],
		"padded-blocks": ["error", "never"],
		"padding-line-between-statements": ["error", {
			blankLine: "always",
			prev: "*",
			next: "return"
		}],
		"quotes": "off",
		"rest-spread-spacing": ["error", "never"],
		"semi": "off",
		"semi-spacing": "error",
		"semi-style": ["error", "last"],
		"space-before-blocks": "error",
		"space-before-function-paren": ["error", "never"],
		"space-in-parens": ["error", "never"],
		"space-infix-ops": "error",
		"space-unary-ops": "off",
		"switch-colon-spacing": ["error", {
			"after": true,
			"before": false
		}],
		"template-curly-spacing": "off",
		"template-tag-spacing": "off",
		"unicode-bom": ["error", "never"],
		"wrap-iife": ["error", "outside"],
		"wrap-regex": "error",
		"yield-star-spacing": "off",
	},
};
